\.py$:           [green,   "\ue606"]
\.(yml|yaml)$:   [magenta, "\uf481"]
\.c$:            [yellow,  "\ue61e"]
\.ai$:           [yellow,  "\ue7b4"]
\.clj$:          [yellow,  "\ue768"]
\.coffee$:       [yellow,  "\uf0f4"]
\.conf$:         [yellow,  "\ue615"]
\.cpp$:          [yellow,  "\ue61d"]
\.css$:          [yellow,  "\ue749"]
\.d$:            [yellow,  "\ue7af"]
\.dart$:         [yellow,  "\ue798"]
\.db$:           [yellow,  "\uf1c0"]
\.diff$:         [yellow,  "\uf440"]
^doc$:           [yellow,  "\uf1c2"]
\.epub$:         [yellow,  "\ue28a"]
\.erl$:          [yellow,  "\ue7b1"]
\.git$:          [cyan,    "\uf1d3"]
\.go$:           [yellow,  "\ue626"]
^gruntfile.js$:  [yellow,  "\ue74c"]
\.hs$:           [yellow,  "\ue777"]
\.html$:         [yellow,  "\uf13b"]
\.iml$:          [yellow,  "\ue7b5"]
\.java$:         [yellow,  "\ue204"]
\.js$:           [yellow,  "\ue74e"]
\.json$:         [yellow,  "\ue60b"]
\.jsx$:          [yellow,  "\ue7ba"]
\.less$:         [yellow,  "\ue758"]
\.log$:          [yellow,  "\uf18d"]
\.lua$:          [yellow,  "\ue620"]
\.md$:           [yellow,  "\uf48a"]
^\.npmignore$:   [yellow,  "\ue71e"]
\.pdf$:          [yellow,  "\uf1c1"]
\.php$:          [yellow,  "\ue73d"]
\.pl$:           [yellow,  "\ue769"]
\.ppt$:          [yellow,  "\uf1c4"]
\.psd$:          [yellow,  "\ue7b8"]
\.r$:            [yellow,  "\uf25d"]
\.rb$:           [yellow,  "\ue21e"]
\.rdb$:          [yellow,  "\ue76d"]
\.sass$:         [yellow,  "\ue603"]
\.scala$:        [yellow,  "\ue737"]
\.styl$:         [yellow,  "\ue600"]
\.tex$:          [yellow,  "\ue600"]
\.ts$:           [yellow,  "\ue628"]
\.twig$:         [yellow,  "\ue61c"]
\.txt$:          [yellow,  "\uf15c"]
\.xls$:          [yellow,  "\uf1c3"]
\.xml$:          [yellow,  "\ue619"]
\.yarn.lock$:    [yellow,  "\ue718"]
\.yml$:          [yellow,  "\uf481"] 
\.zip$:          [yellow,  "\uf410"]

\.\.:            [blue,    "\uf115"]
\.:              [blue,    "\uf115"]

$file:           [blue,    "\uf15b"]
$dir:            [blue,    "\uf115"]